const pdf = require('pdf-parse');
const { generateQuizFromText } = require('../utils/aiHelper');

exports.generateQuiz = async (req, res) => {
    try {
        // Step 1: Check if file was uploaded
        // Step 1: Check karna ki file aayi hai ya nahi 
        // 'pdfFile' woh naam hai jo humne frontend (FormData) mein diya tha
        if (!req.file) {
            return res.status(400).json({
                success: false,
                message: "No file uploaded. Please upload a PDF.",
            });
        }

        // Step 2: Extract text from PDF
        const data = await pdf(req.file.buffer);
        const text = data.text;

        if (!text || text.trim() === "") {
            return res.status(400).json({
                success: false,
                message: "Could not extract text from the PDF. The PDF might be empty or scanned."
            });
        }
        
        // Step 3: Call the AI to generate quiz from extracted text with timeout protection
        console.log("Sending text to AI for quiz generation...");
        console.log(`Text length: ${text.length} characters`);
        
        // Add timeout to prevent hanging
        const quizGenerationPromise = generateQuizFromText(text);
        const timeoutPromise = new Promise((_, reject) => {
            setTimeout(() => reject(new Error("AI generation timeout after 30 seconds")), 30000);
        });
        
        const quiz = await Promise.race([quizGenerationPromise, timeoutPromise]);

        if (!quiz) {
            return res.status(500).json({
                success: false,
                message: "The AI could not generate a quiz from the provided text."
            });
        }

        // Step 4: Send the actual quiz in response
        return res.status(200).json({
            success: true,
            message: "Quiz generated successfully!",
            quiz: quiz, // Send the actual quiz generated by AI
            extractedText: text.substring(0, 300) + "..." // Optional: for debugging
        });

    } catch (error) {
        console.error("Error in generating quiz:", error);
        return res.status(500).json({
            success: false,
            message: "Server error while generating quiz. Please try again.",
            error: error.message,
        });
    }
};